# Generated by Django 5.0.6 on 2024-07-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/defalut_profile.jpg', upload_to='images/'),
        ),
    ]
