# Generated by Django 5.0.6 on 2024-07-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/img/user.png', upload_to='images/'),
        ),
    ]
