# Generated by Django 5.0.6 on 2024-07-09 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0025_animal_ranking_voter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Forum_answer', to='pybo.forumquestion'),
        ),
        migrations.DeleteModel(
            name='Profile_img',
        ),
    ]
