# Generated by Django 5.0.6 on 2024-07-10 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0026_alter_forumanswer_question_delete_profile_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_ranking',
            name='voter_count',
        ),
        migrations.AddField(
            model_name='animal_ranking',
            name='vote_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='animal_ranking',
            name='voter',
            field=models.ManyToManyField(related_name='voter_animal_ranking', to=settings.AUTH_USER_MODEL),
        ),
    ]
