# Generated by Django 5.0.6 on 2024-07-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0027_remove_animal_ranking_voter_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_ranking',
            old_name='vote_count',
            new_name='voter_count',
        ),
    ]
